import { OrbInfo, Boss } from './types';

// The 12 Orbs with exact OneNote parameters
export const INITIAL_ORBS: OrbInfo[] = [
  {
    id: 'orange',
    name: 'Orange Orb',
    color: 'Orange',
    hex: '#f97316',
    textColor: 'text-orange-500',
    rarity: 'Common',
    baseRarityWeight: 0.35,
    abilityDescription: 'Add +1 extra guess for 1 match without reducing your orb rewards.'
  },
  {
    id: 'blue',
    name: 'Blue Orb',
    color: 'Blue',
    hex: '#3b82f6',
    textColor: 'text-blue-500',
    rarity: 'Common',
    baseRarityWeight: 0.30,
    abilityDescription: 'Submerge: Scramble the boss secret passcode into a new combination. (Only usable during first 5 turns).'
  },
  {
    id: 'green',
    name: 'Green Orb',
    color: 'Green',
    hex: '#22c55e',
    textColor: 'text-green-500',
    rarity: 'Common',
    baseRarityWeight: 0.25,
    abilityDescription: 'Reveal Absent: Scan the puzzle and reveal 1 color that is NOT in the Secret Combo.'
  },
  {
    id: 'silver',
    name: 'Silver Orb',
    color: 'Silver',
    hex: '#94a3b8',
    textColor: 'text-slate-400',
    rarity: 'Common',
    baseRarityWeight: 0.10,
    abilityDescription: '+15% chance of receiving Uncommon loot after winning a match.'
  },
  {
    id: 'red',
    name: 'Red Orb',
    color: 'Red',
    hex: '#ef4444',
    textColor: 'text-red-500',
    rarity: 'Uncommon',
    baseRarityWeight: 0.35,
    abilityDescription: 'Burn: Scans the target and reveals the exact color of 1 random spot.'
  },
  {
    id: 'purple',
    name: 'Purple Orb',
    color: 'Purple',
    hex: '#a855f7',
    textColor: 'text-purple-500',
    rarity: 'Uncommon',
    baseRarityWeight: 0.20,
    abilityDescription: 'Add +2 extra guesses for 1 match without reducing your orb rewards.'
  },
  {
    id: 'yellow',
    name: 'Yellow Orb',
    color: 'Yellow',
    hex: '#eab308',
    textColor: 'text-yellow-500',
    rarity: 'Uncommon',
    baseRarityWeight: 0.35,
    abilityDescription: 'Disable Boss Penalty: Nullifies the hostile passive of the current Boss for this round!'
  },
  {
    id: 'gold',
    name: 'Gold Orb',
    color: 'Gold',
    hex: '#fbbf24',
    textColor: 'text-amber-500',
    rarity: 'Uncommon',
    baseRarityWeight: 0.10,
    abilityDescription: '+20% chance of receiving Rare loot after winning a match.'
  },
  {
    id: 'pink',
    name: 'Pink Orb',
    color: 'Pink',
    hex: '#ec4899',
    textColor: 'text-pink-500',
    rarity: 'Rare',
    baseRarityWeight: 0.10,
    abilityDescription: '1.75x Orb Multiplier: Multiplies all fragments awarded at the end of the match by 1.75!'
  },
  {
    id: 'white',
    name: 'White Orb',
    color: 'White',
    hex: '#f8fafc',
    textColor: 'text-white border border-slate-600',
    rarity: 'Rare',
    baseRarityWeight: 0.30,
    abilityDescription: 'Add +3 extra guesses for 1 match without reducing your orb rewards.'
  },
  {
    id: 'black',
    name: 'Black Orb',
    color: 'Black',
    hex: '#111827',
    textColor: 'text-slate-900 border border-slate-300 shadow shadow-purple-500',
    rarity: 'Rare',
    baseRarityWeight: 0.50,
    abilityDescription: 'Hint Location: Reveals whether a selected spot matches a target color.'
  },
  {
    id: 'teal',
    name: 'Teal Orb',
    color: 'Teal',
    hex: '#14b8a6',
    textColor: 'text-teal-500',
    rarity: 'Rare',
    baseRarityWeight: 0.10,
    abilityDescription: '2.25x Orb Multiplier: Multiplies all fragments awarded at the end of the match by 2.25!'
  }
];

// Campaign Progression: The 10 Bosses mapping exactly to the design document specs
export const BOSS_CAMPAIGN: Boss[] = [
  {
    id: 'boss_1',
    name: 'Lemons',
    title: 'The "Helpful" Gremlin',
    description: 'A mischievous round yellow lemon gremlin who places sticky notes and claims to be "helping" you decode his zesty pegboard.',
    imageTheme: 'from-amber-300 to-yellow-500 text-yellow-950',
    orbsMax: 5, // length of guess code
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red'],
    lootCommonChan: 1.0,
    lootUncommonChan: 0.0,
    lootRareChan: 0.0,
    bossSpecialDescription: 'The Zesty Lab: Bright tiled room, giant peg-board wall, and bubbling citrus vats surround the arena.',
    dialogueIntro: "Hey! Don't sour on me! I'm here helping! PATTERN? WHAT PATTERN? Guess again, loser!",
    dialogueDefeat: 'Aww, you squashed me! Go ahead, make your sweet lemonade out of my fragments!',
    dialogueVictory: 'Bitter failure for you! Tangy victory for Lemons! Guess again, loser!',
    portraitUrl: '/Images/boss_assets/Boss 1 - Lemons.png',
    stageBgUrl: '/Images/boss_assets/Boss 1 - Lemons Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/zesty-lab-bubbling-vats/800/450',
    hexTheme: '#fbbf24'
  },
  {
    id: 'boss_2',
    name: 'Templefrist',
    title: 'The Sandstone Sentinel',
    description: 'An ancient mossy construct standing guard over the secret sandstone archives.',
    imageTheme: 'from-orange-250 to-amber-700 text-amber-50',
    orbsMax: 5,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple'],
    lootCommonChan: 0.90,
    lootUncommonChan: 0.10,
    lootRareChan: 0.0,
    bossSpecialDescription: 'Vents standard dust clouds, adding moderate visual haze to the console.',
    dialogueIntro: "Halt! You wish to traverse the sandstone passage? Answer my ancient colored riddle first!",
    dialogueDefeat: 'The stones slide apart... You possess excellent decoding wisdom, traveler.',
    dialogueVictory: 'Enclosed forever! Your bones shall feed the dust bunnies of Templefrist!',
    portraitUrl: '/Images/boss_assets/Boss 2 - Templefrist.png',
    stageBgUrl: '/Images/boss_assets/Boss 2 - Templefrist Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/sandstoneruins/800/450',
    hexTheme: '#d97706'
  },
  {
    id: 'boss_3',
    name: 'Bigginsly',
    title: 'The Clockwork Titan',
    description: 'A massive mechanical clockwork bot with gears clicking. Generates steam exhaust.',
    imageTheme: 'from-neutral-400 to-zinc-700 text-neutral-100',
    orbsMax: 5,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow'],
    lootCommonChan: 0.80,
    lootUncommonChan: 0.20,
    lootRareChan: 0.0,
    bossSpecialDescription: 'Steam Hiss: Emits thick gas bubbles that occasionally bubble on the screen.',
    dialogueIntro: "BZZT... CLANK! Machine online. Logic density levels maximized. Commencing pattern-blocking protocol!",
    dialogueDefeat: 'SYSTEM FATAL... Springs popping... structural gear alignment compromised... oil leaks detected...',
    dialogueVictory: 'Steam-rolled! Human synapses cannot match clockwork mechanical synchronization!',
    portraitUrl: '/Images/boss_assets/Boss 3 - Bigginsly.png',
    stageBgUrl: '/Images/boss_assets/Boss 3 - Bigginsly Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/steamfactory/800/450',
    hexTheme: '#71717a'
  },
  {
    id: 'boss_4',
    name: 'Nanomic',
    title: 'The Viral Hive Grid',
    description: 'A micro-swarm of neon cybernetic insects behaving as a single hivemind.',
    imageTheme: 'from-cyan-400 to-blue-600 text-cyan-50',
    orbsMax: 5,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold'],
    lootCommonChan: 0.70,
    lootUncommonChan: 0.20,
    lootRareChan: 0.10,
    bossSpecialDescription: 'Cybernetic Haze: Matching algorithms stutter. Adds digital screen glitches.',
    dialogueIntro: "We are the swarm. Standard binary thoughts are useless against our cloud algorithm. Prepare for digitization!",
    dialogueDefeat: 'Connection lost... WiFi failure... Nanomic swarm scattered into pixelated white noise.',
    dialogueVictory: 'Your cognitive capacity was insufficient. Sucking up your code variables into our backup drive.',
    portraitUrl: '/Images/boss_assets/Boss 4 - Nanomic.png',
    stageBgUrl: '/Images/boss_assets/Boss 4 - Nanomic Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/cyberterminal/800/450',
    hexTheme: '#06b6d4'
  },
  {
    id: 'boss_5',
    name: 'Natty D',
    title: 'The Cyber-Retro Dealer',
    description: 'A glowing synthwave card dealer offering a futuristic casino layout.',
    imageTheme: 'from-fuchsia-500 to-violet-800 text-fuchsia-100',
    orbsMax: 5,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold', 'pink'],
    lootCommonChan: 0.40,
    lootUncommonChan: 0.50,
    lootRareChan: 0.10,
    bossSpecialDescription: 'Casino Lights: Blinks with vibrant fluorescent strobe lights to excite the board.',
    dialogueIntro: "Hey there, high roller! Place your bets on our nine-color board. House is ready to deal!",
    dialogueDefeat: 'Unbelievable! You read my sleight of hand flawlessly. Here are your chips, champ!',
    dialogueVictory: 'Dealer wins! That is a bust for you. Better luck in the next game, kiddo!',
    portraitUrl: '/Images/boss_assets/Boss 5 - Natty D.png',
    stageBgUrl: '/Images/boss_assets/Boss 5 - Natty D Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/synthwavegrid/800/450',
    hexTheme: '#d946ef'
  },
  {
    id: 'boss_6',
    name: 'Pretty Pea',
    title: 'The Toxic Flora Queen',
    description: 'A beautifully dangerous carnivorous plant diva from the core jungle. Has strict entry fragment rules.',
    imageTheme: 'from-emerald-300 to-teal-800 text-emerald-50',
    orbsMax: 5,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold', 'pink', 'white'],
    lootCommonChan: 0.15,
    lootUncommonChan: 0.65,
    lootRareChan: 0.20,
    requiredFragments: { yellow: 200, orange: 200, purple: 100, blue: 100 },
    bossSpecialDescription: 'Spore Lock: Entry demands a toll of Yellow x200, Orange x200, Purple x100, Blue x100 fragments!',
    dialogueIntro: "How dare you disturb my botanical salon! Only high-class codebreakers offering yellow and orange nectars may fight!",
    dialogueDefeat: 'Ugh! My lovely petals are falling... You proved to be a gardener of peerless intellect...',
    dialogueVictory: 'Mmm! Beautiful, fresh organic compost! You will nourish my jungle vines for centuries!',
    portraitUrl: '/Images/boss_assets/Boss 6 - Pretty Pea.png',
    stageBgUrl: '/Images/boss_assets/Boss 6 - Pretty Pea Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/botanicallab/800/450',
    hexTheme: '#10b981'
  },
  {
    id: 'boss_7',
    name: 'Sir Louie',
    title: 'The Iron-Hulled Guard',
    description: 'A royal knight in silver-alloy plate armor guarding the sovereign gold chambers.',
    imageTheme: 'from-slate-400 to-slate-800 text-slate-100',
    orbsMax: 5,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold', 'pink', 'white', 'black'],
    lootCommonChan: 0.05,
    lootUncommonChan: 0.65,
    lootRareChan: 0.30,
    requiredFragments: { red: 100, green: 100, blue: 100, black: 75 },
    bossSpecialDescription: 'Chamber Toll: Gated behind Red x100, Green x100, Blue x100, Black x75 fragments!',
    dialogueIntro: "By the King's order, stop right there! Pay the knight toll of crimson, jade, sapphire, and obsidian!",
    dialogueDefeat: 'Impressive armor puncture! You broke my secret vault code masterfully. Carry on!',
    dialogueVictory: 'My iron shield stands undefeated! Begone from the royal master chambers, intruder!',
    portraitUrl: '/Images/boss_assets/Boss 7 - Sir Louie.png',
    stageBgUrl: '/Images/boss_assets/Boss 7 - Sir Louie Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/kingstreasury/800/450',
    hexTheme: '#64748b'
  },
  {
    id: 'boss_8',
    name: 'Queen Asabeth',
    title: 'The Shadow Spider Empress',
    description: 'A terrifying eight-legged queen weaving webs in total abyss. Code length grows to 6 slots!',
    imageTheme: 'from-slate-900 to-stone-900 text-purple-200 border-2 border-purple-900',
    orbsMax: 6, // Length is now 6 orbs!
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold', 'pink', 'white', 'black', 'teal'],
    lootCommonChan: 0.0,
    lootUncommonChan: 0.45,
    lootRareChan: 0.55,
    requiredFragments: { black: 100, teal: 20, blue: 150, red: 150 },
    bossSpecialDescription: 'Shadow Net: Gated (Black x100, Teal x20, Blue x150, Red x150). Completely disables use of Black Orbs (Hint ability is blocked unless you use a Yellow Orb to negate her passive)!',
    dialogueIntro: "In my dark web, those who seek truth find only spiders. Your Obsidian Hint Orbs are useless here!",
    dialogueDefeat: "My webs have been severed! The light... it is too bright... children, retreat!",
    dialogueVictory: 'Wrapped in sticky silk threads, a delicious prize for my cocoon nurseries!',
    portraitUrl: '/Images/boss_assets/Boss 8 - Queen Asabeth.png',
    stageBgUrl: '/Images/boss_assets/Boss 8 - Queen Asabeth Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/darkcavern/800/450',
    hexTheme: '#8b5cf6'
  },
  {
    id: 'boss_9',
    name: 'Elkgore',
    title: 'The Frostfire Storm Druid',
    description: 'An ancient shaman of the high peaks who channels storms. Code length is 6 slots.',
    imageTheme: 'from-sky-700 to-indigo-950 text-indigo-100 border-2 border-indigo-700',
    orbsMax: 6,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold', 'pink', 'white', 'black', 'teal'],
    lootCommonChan: 0.0,
    lootUncommonChan: 0.35,
    lootRareChan: 0.65,
    requiredFragments: { pink: 100, white: 100, yellow: 300, purple: 150 },
    bossSpecialDescription: 'Blizzard Scramble: Gated (Pink x100, White x100, Yellow x300, Purple x150). Will automatically scramble the secret combination once during the first 5 turns (Unless negated by Yellow Orb)!',
    dialogueIntro: "Welcome to the frozen wastes! The cold winds reshape the secret answer pattern as we play!",
    dialogueDefeat: 'The storm clears... my staff is shattered... the northern lights shine on your final answer...',
    dialogueVictory: 'Frostbitten! Your brain synapses froze solid before they could finish the puzzle!',
    portraitUrl: '/Images/boss_assets/Boss 9 - Elkgore.png',
    stageBgUrl: '/Images/boss_assets/Boss 9 - Elkgore Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/frostpeaks/800/450',
    hexTheme: '#0ea5e9'
  },
  {
    id: 'boss_10',
    name: 'Mad Martin',
    title: 'The Great MindMaster Creator',
    description: 'The supreme mastermind creator who designed the entire orb grid. The final ultimate duel.',
    imageTheme: 'from-purple-900 to-black text-rose-200 border-4 border-rose-600',
    orbsMax: 6,
    allowedColors: ['orange', 'blue', 'green', 'silver', 'red', 'purple', 'yellow', 'gold', 'pink', 'white', 'black', 'teal'],
    lootCommonChan: 0.0,
    lootUncommonChan: 0.0,
    lootRareChan: 1.0,
    requiredFragments: { pink: 150, white: 150, black: 150, teal: 150 },
    bossSpecialDescription: 'Greedy Thief: Gated (Pink x150, White x150, Black x150, Teal x150). Instantly deducts 1 from your remaining turns whenever you get a color or placement correct as "theft cost" (Unless negated by Yellow Orb)!',
    dialogueIntro: "Aha! You face the supreme creator of the master orbs! Every clue you solve feeds my machinery, reducing your turns count!",
    dialogueDefeat: "My masterpiece... undone... by a mortal logic scanner! Truly, you are the ultimate MindMaster!",
    dialogueVictory: "My calculation matrix remains peak! Your intellect has been archived as standard test code!",
    portraitUrl: '/Images/boss_assets/Boss 10 - Mad Martin.png',
    stageBgUrl: '/Images/boss_assets/Boss 10 - Mad Martin Arena.png',
    fallbackBgUrl: 'https://picsum.photos/seed/clockworkuniverse/800/450',
    hexTheme: '#f43f5e'
  }
];
